# Generated by Django 5.1.7 on 2025-03-22 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_follow_alter_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_images', verbose_name='Аватар'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='follow',
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
    ]
