# Generated by Django 5.1.7 on 2025-04-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_weight_amount_amount'),
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseList',
            new_name='Cart',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'follower')},
        ),
    ]
