# Generated by Django 5.1.7 on 2025-04-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_weight_amount_amount'),
        ('users', '0006_alter_cart_recipe_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_recipe', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
