# Generated by Django 5.1.7 on 2025-03-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Соль', 'Соль'), ('Свёкла', 'Свёкла'), ('Сельдерей', 'Сельдерей'), ('Курятина', 'Курятина'), ('Сливки', 'Сливки'), ('Молоко', 'Молоко'), ('Вода', 'Вода'), ('Перец', 'Перец'), ('Кетчуп', 'Кетчуп'), ('Майонез', 'Майонез'), ('Колбаса', 'Колбаса'), ('Сыр', 'Сыр'), ('Фарш', 'Фарш'), ('Тесто', 'Тесто'), ('Масло', 'Масло')], max_length=30, verbose_name='Название')),
                ('measure', models.CharField(max_length=15, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Описание')),
                ('time', models.IntegerField(verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
