# Generated by Django 5.1.7 on 2025-03-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_amount_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='weight',
            new_name='amount',
        ),
    ]
